[tool.ruff]
line-length = 150 # par exemple
fix = true        # activer les corrections automatiques
show-fixes = true

[tool.ruff.lint]
select = ["E", "F", "W", "C90"]  # E=pycodestyle, F=pyflakes, W=warnings, etc.
